import { S3Client, PutObjectCommand, GetObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import dotenv from "dotenv";
import crypto from "crypto";

dotenv.config();

// Shared S3 client for product images (used by the product routes and the
// seed script). Created on first use so scripts can load their .env first.
let client;
const getS3 = () => {
  client ||= new S3Client({
    credentials: {
      accessKeyId: process.env.AWS_ACCESS_KEY_ID,
      secretAccessKey: process.env.AWS_ACCESS_KEY_SECRET,
    },
    region: process.env.AWS_REGION,
  });
  return client;
};

const hashedImageName = (bytes = 32) => crypto.randomBytes(bytes).toString("hex");

// Uploads an image and returns its S3 key, which is what Product.image stores.
export const uploadImageToS3 = async ({ buffer, mimetype }) => {
  const imageName = hashedImageName();
  await getS3().send(
    new PutObjectCommand({
      Bucket: process.env.BUCKET_NAME,
      Key: imageName,
      Body: buffer,
      ContentType: mimetype,
    })
  );
  return imageName;
};

// Image keys are generated by uploadImageToS3 (hex) or were uploaded with a
// plain file name; anything else is rejected so arbitrary paths can't be signed.
export const isValidImageKey = (key) =>
  typeof key === "string" && /^[A-Za-z0-9][A-Za-z0-9._-]{0,199}$/.test(key);

// Time-limited link to a private image. Signing happens locally (no request to
// AWS) and needs s3:GetObject on the bucket.
export const signedImageUrl = (key, expiresIn = 3600) =>
  getSignedUrl(
    getS3(),
    new GetObjectCommand({ Bucket: process.env.BUCKET_NAME, Key: key }),
    { expiresIn }
  );
